services:
  valkey:
    image: valkey/valkey:alpine
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"
    volumes:
      - redis-data:/data

  api1: &app
    build:
      context: .
    container_name: api1
    networks:
      - backend
      - payment-processor
    restart: always
    environment:
      REDIS_CONN: valkey
      PROCESSOR: true
    depends_on:
      - valkey
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "155MB"

  api2:
    <<: *app
    environment:
      REDIS_CONN: valkey
      PROCESSOR: false
    container_name: api2

  nginx:
    image: nginx:1.29.0-alpine
    volumes:
      - $PWD/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

volumes:
  redis-data:

networks:
  backend:
  payment-processor:
    external: true
